version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-vk
    networks:
      - app-network
    hostname: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: ./env_files/postgres.env

  vk-api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: python app/application.py
    networks:
      - app-network
    depends_on:
      - "postgres"
    links:
      - postgres
    image: vk-api
    container_name: vk-api
    env_file:
      - ./env_files/postgres.env
      - ./env_files/general.env
    volumes:
      - ./logs:/app/logs
    ports:
      - "177:5000"

networks:
  app-network:
    driver: bridge
